trigger:
  - master

pool:
  name: rohil-practice-pool

stages:

  - stage: terraform_stage

    jobs:

      - job: InitJob
        displayName: Install and Init Job

        steps:

          - task: TerraformInstaller@1

            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5

            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'rohil-sc'
              backendAzureRmResourceGroupName: 'yaml-rg'
              backendAzureRmStorageAccountName: 'tfstatecentral12345'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'prod.terraform.tfstate'
      - job: ValidateJob
        displayName: Terraform Validate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
      - job: PlanJob
        displayName: terraform Plan
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'rohil-sc'
      - job: ApplyJob
        displayName: Terraform Apply
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'rohil-sc'